apiVersion: v1
kind: Service
metadata:
  name: mysql-rating
  labels:
    app: mysql-rating
spec:
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  selector:
    app: mysql-rating