apiVersion: v1
kind: Service
metadata:
  name: mysql-catering
  labels:
    app: mysql-catering
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql-catering