apiVersion: v1
kind: Service
metadata:
  name: mysql-notification
  labels:
    app: mysql-notification
spec:
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  selector:
    app: mysql-notification