apiVersion: v1
kind: Service
metadata:
  name: mysql-statistic
  labels:
    app: mysql-statistic
spec:
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3306
  selector:
    app: mysql-statistic