version: '2'
services:
    user-service:
        container_name: user-service
        image: user-service-build
        ports:
            - "8081:8081"
        networks:
            - custom-network
    catering-service:
            container_name: catering-service
            image: catering-service-build
            ports:
                - "8082:8082"
            networks:
                - custom-network
    gateway-service:
            container_name: gateway-service
            image: gateway-service-build
            ports:
                - "8080:8080"
            depends_on:
              - user-service
              - catering-service
            networks:
                - custom-network
            links:
              - user-service:user_service
              - catering-service:catering_service
            environment:
              - authServiceUrl=http://user_service:8081
              - userServiceUrl=http://user_service:8081
              - cateringServiceZrl=http://catering_service:8082
networks:
    custom-network:
        driver: bridge
