apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-notification
  labels:
    app: mysql-notification
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-notification
  template:
    metadata:
      labels:
        app: mysql-notification
    spec:
      containers:
      - name: mysql-notification
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test123
        - name: MYSQL_DATABASE
          value: app
        ports:
        - containerPort: 3306
          name: mysql-notif
        volumeMounts:
        # name must match the volume name below
        - name: mysql-persistent-storage-notif
          # mount path within the container
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-notif
        persistentVolumeClaim:
          claimName: mysql-pvc-notification