apiVersion: v1
kind: Service
metadata:
  name: catering-service
  labels:
    app: catering-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: catering-service
  type: LoadBalancer
