apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: notification-service
  type: LoadBalancer
