apiVersion: v1
kind: Service
metadata:
  labels:
    app: rating-service
  name: rating-service
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    app: rating-service
  type: LoadBalancer
