apiVersion: v1
kind: Service
metadata:
  name: fakesmtp-service
  labels:
    app: fakesmtp-service
spec:
  ports:
    - port: 25
      targetPort: 25
  selector:
    app: fakesmtp-service
  type: LoadBalancer
