apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-statistic
  labels:
    app: mysql-statistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-statistic
  template:
    metadata:
      labels:
        app: mysql-statistic
    spec:
      containers:
      - name: mysql-statistic
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test123
        - name: MYSQL_DATABASE
          value: app
        ports:
        - containerPort: 3309
          name: mysql
        volumeMounts:
        # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-statistic