kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-statistic
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi