apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger-service
  name: swagger-service
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: swagger-service
  type: LoadBalancer
