apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: user-service-app
    spec:
      containers:
      - image: eu.gcr.io/cateringunitmonitor/user-service-build
        name: user-service-app
        ports:
        - containerPort: 8081

