apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway-service
  name: api-gateway-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: api-gateway-service
status:
  loadBalancer: {}
