version: '3'
services:
    mysql-server:
        container_name: mysql-server
        image: mysql/mysql-server
        ports:
          - "3036:3036"
        environment:
          - MYSQL_DATABASE=app
          - MYSQL_ROOT_PASSWORD=test123
          - MYSQL_USER=user
          - MYSQL_PASSWORD=test123
        networks:
          - custom-network
    user-service:
        container_name: user-service
        image: user-service-build
        ports:
            - "8081:8081"
        networks:
            - custom-network
        depends_on:
          - rabbitmq
          - mysql-server
        links:
          - mysql-server:mysql
          - rabbitmq:rabbitmq
    catering-service:
            container_name: catering-service
            image: catering-service-build
            ports:
                - "8082:8082"
            networks:
                - custom-network
            depends_on:
              - rabbitmq
              - mysql-server
            links:
              - mysql-server:mysql
              - rabbitmq:rabbitmq
    api-gateway-service:
            container_name: api-gateway-service
            image: api-gateway-service-build
            ports:
              - "80:80"
            depends_on:
              - user-service
              - catering-service
              - mysql-server
              - notification-service
              - rating-service
            networks:
              - custom-network
            links:
              - user-service:user-service
              - user-service:authentication-service
              - catering-service:catering-service
              - notification-service:notification-service
              - rating-service:rating-service
            environment:
              - authServiceUrl=http://user-service:8081
              - userServiceUrl=http://user-service:8081
              - cateringServiceUrl=http://catering-service:8082
              - notificationServiceUrl=http://notification-service:8084
              - ratingServiceUrl=http://rating-service:8085
    swagger-service:
      container_name: swagger-service
      image: swagger-service-build
      ports:
        - "8083:8083"
      depends_on:
        - user-service
        - catering-service
        - mysql-server
      networks:
        - custom-network
      links:
        - user-service:user-service
        - user-service:authentication-service
        - catering-service:catering-service
        - rating-service:rating-service
      environment:
        - authServiceUrl=http://localhost:8081
        - userServiceUrl=http://localhost:8081
        - cateringServiceUrl=http://localhost:8082
        - notificationServiceUrl=http://localhost:8084
        - ratingServiceUrl=http://localhost:8085
    notification-service:
      container_name: notification-service
      image: notification-service-build
      ports:
        - "8084:8084"
      depends_on:
        - mysql-server
        - user-service
      networks:
        - custom-network
      links:
        - user-service:user_service
        - fakesmtp:fakesmtp
      environment:
        - authServiceUrl=http://user-service:8081
        - userServiceUrl=http://user-service:8081
        - smtpUrl=fakesmtp
        - smtpPort=25
    fakesmtp:
      container_name: fakesmtp
      image: munkyboy/fakesmtp
      ports:
        - "25:25"
      networks:
        - custom-network
      volumes:
        - /c/tmp:/var/mail
    rating-service:
      container_name: rating-service
      image: rating-service-build
      ports:
        - "8085:8085"
      depends_on:
        - user-service
        - catering-service
        - rabbitmq
        - mysql-server
      networks:
        - custom-network
      links:
        - user-service:user-service
        - catering-service:catering-service
        - mysql-server:mysql
        - rabbitmq:rabbitmq
      environment:
        - userServiceUrl=http://user-service:8081
        - authServiceUrl=http://user-service:8081
        - cateringServiceUrl=http://catering-service:8082
    rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - custom-network

networks:
    custom-network:
        driver: bridge
