version: '2.1'
services:
    mysql-server:
        container_name: mysql-server
        image: mysql-server
        ports:
          - "3036:3036"
        environment:
          - MYSQL_DATABASE=app
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_USER=user
          - MYSQL_PASSWORD=test123
        networks:
          - custom-network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    user-service:
        container_name: user-service
        image: user-service-build
        ports:
            - "8081:8081"
        networks:
            - custom-network
        depends_on:
          mysql-server:
            condition: service_healthy
        links:
          - mysql-server:mysql
    catering-service:
            container_name: catering-service
            image: catering-service-build
            ports:
                - "8082:8082"
            networks:
                - custom-network
            depends_on:
              mysql-server:
                condition: service_healthy
            links:
              - mysql-server:mysql
    gateway-service:
            container_name: gateway-service
            image: gateway-service-build
            ports:
                - "8080:8080"
            depends_on:
              - user-service
              - catering-service
              - mysql-server
            networks:
                - custom-network
            links:
              - user-service:user-service
              - catering-service:catering-service
            environment:
              - authServiceUrl=http://user-service:8081
              - userServiceUrl=http://user-service:8081
              - cateringServiceUrl=http://catering-service:8082
networks:
    custom-network:
        driver: bridge
