apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  ports:
  - name: "3036"
    port: 3036
    targetPort: 3036
  selector:
    io.kompose.service: mysql-server
status:
  loadBalancer: {}
