apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    io.kompose.service: notification-service
status:
  loadBalancer: {}
