apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Programs\kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: user-service
status:
  loadBalancer: {}
